apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store-app
spec:
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - name: app
          image: "petstore:test"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 3001
              procotol: TCP
