apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psql
  selector:
    app: petstore-database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-scripts
data:
  createTable.sql: |-
    CREATE TABLE IF NOT EXISTS orders (order_id BIGSERIAL PRIMARY KEY, pet_id BIGINT NOT NULL, quantity INTEGER NOT NULL, ship_date BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000), status TEXT NOT NULL, complete BOOLEAN NOT NULL);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-database
spec:
  selector:
    matchLabels:
      app: petstore-database
  template:
    metadata:
      labels:
        app: petstore-database
    spec:
      volumes:
        - name: pg-scripts
          configMap:
            name: pg-scripts
      containers:
        - name: app
          image: "postgres:16-alpine"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: pg-scripts
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: password123
