apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 3000
      protocol: TCP
      name: psql
  selector:
    app: petstore-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-database
spec:
  selector:
    matchLabels:
      app: petstore-database
  template:
    metadata:
      labels:
        app: petstore-database
    spec:
      containers:
        - name: app
          image: "postgres:16-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: password123
