apiVersion: v1
kind: Service
metadata:
  name: pet-store-svc
  app: pet-store
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: metrics
  selector:
    app: pet-store
