apiVersion: v2
name: pet-store
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "58.1.1"
    alias: prometheus
  - name: jaeger-all-in-one
    repository: "https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts"
    version: "0.1.12"
    alias: jaeger