jaeger:
  enableHttpOpenTelemetryCollector: true

prometheus:
  fullnameOverride: "prometheus"
  
  defaultRules:
    create: false

  ## We don't care about this for now
  alertmanager:
    enabled: false

  # We want grafana
  grafana:
    fullnameOverride: 'grafana'
    enabled: true
    adminPassword: password

  # We want service monitors
  kubernetesServiceMonitors:
    enabled: true

  coreDns:
    fullnameOverride: 'coreDns'
    enabled: true

  kubeDns:
    fullnameOverride: 'kubeDns'
    enabled: false

  prometheusOperator:
    fullnameOverride: 'prometheus-operator'
    enabled: true

  prometheus:
    fullnameOverride: 'prometheus'
    enabled: true

    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false

      serviceMonitorSelector:
        matchLabels:
          metrics: prometheus

  thanosRuler:
    enabled: false